#!/bin/bash
. $(dirname "$0")/lib-common

[[ "$#" == 0 ]] && log-error "No configure command" && exit

load-config
if [[ "$MODE" == sym ]]; then
    . $(dirname "$0")/lib-sym
    setup-kllvm
    inject-cxxflags
    inject-compilers
else
    . $(dirname "$0")/lib-dyn
    setup-allvm
    inject-compilers
fi

run-program "$@"
